import React from 'react';
import QRCode from 'qrcode.react'

import './App.css'

function App() {
  const protocol = {
    protocol: 'SimpleWallet',   // procotol name, wallet used to distinguish different protocols, this protocol is SimpleWallet
    version: '1.0',   // Protocol version information, such as 1.0
    dappName: 'eosfinex',   // dapp name
    dappIcon: '',   // dapp Icon
    action: 'login',   // The assignment for login
    uuID: '12345',   // The unique id generated by dapp server for this login verification
    loginUrl: 'https://eosfinex.com/test',   // The url on dapp server to accept the login validation information
    expired: new Date().getTime() + (60 * 60 * 24),   // Qr code expiration time, unix timestamp
    loginMemo: 'this is a memo',   // Login note information, wallet for display, optional
  }

  return (
    <div className="App">
      <header className="App-header">
        <QRCode value={JSON.stringify(protocol)} />
        <br />
        <br />
        <pre>
           {JSON.stringify(protocol, null, 2)}
        </pre>
      </header>
    </div>
  );
}

export default App